
include $(GNUSTEP_MAKEFILES)/common.make

GNUSTEP_MAKEINFO_FLAGS = -D NO-TEXI2HTML

DOCUMENT_NAME = manual

manual_TEXI_FILES =              \
	manual.texi              \
	foreword.texi            \
	Introduction.texi        \
        ObjcLanguage.texi        \
	WritingNewClasses.texi   \
	WorkingWithObjects.texi  \
	DistributedObjects.texi  \
	AdvancedTopics.texi      \
	Glossary.texi            \
	ExampleCode.texi         \
	GNUstepMake.texi         \
	ObjcAndJava.texi         \
	JavaAndGuile.texi

manual_DOC_INSTALL_DIR = Developer/Base/ProgrammingManual

include $(GNUSTEP_MAKEFILES)/documentation.make


