
include $(GNUSTEP_MAKEFILES)/common.make

GNUSTEP_MAKEINFO_FLAGS = -D NO-TEXI2HTML

DOCUMENT_NAME = manual

manual_TEXI_FILES =              \
	foreword.texi            \
	manual.texi              \
	AdvancedMessaging.texi   \
	BaseLibrary.texi         \
	Compliance.texi          \
	DistributedObjects.texi  \
	ExceptionHandling.texi   \
	GNUstepMake.texi         \
	GSDoc.texi               \
	Introduction.texi        \
	ObjcAndJavaC++.texi      \
	ObjcLanguage.texi        \
	JavaAndGuile.texi        \
	WorkingWithObjects.texi  \
	WritingNewClasses.texi

manual_DOC_INSTALL_DIR = Developer/Base/ProgrammingManual

include $(GNUSTEP_MAKEFILES)/documentation.make


