#!/bin/sh -e

# The directory in which to find the last snapshot
dir=${HOME}/gnu/releases

# The name of this module
module=gstep-base

. Version

cvs -Q rtag -F release-`echo ${VERSION} | tr . -`  $module

make dist

mv -f ${module}-${VERSION}.tar.gz $dir
