#!/bin/sh -e

dir=/com/share/ftp/roland

module=libc

date=`date +%y%m%d`
snap=${module}-${date}

cvs -Q rtag -F $snap $module

rm -rf $snap
cvs -Q checkout -d $snap -r $snap $module
tar -f - -co $snap | gzip -9v -c > $snap.tar.gz

find $snap \( -name CVS -prune \) -o \( -type f -print \) |
xargs md5sum | gzip -9v -c > $snap.md5sum.gz

rm -rf $snap &

mv -f $snap.tar.gz $snap.md5sum.gz $dir
