#!/bin/sh -e

# The directory in which to find the last snapshot
dir=/home/mccallum/gnu/releases

# The name of this module
module=gstep-base

date=`date +%y%m%d`
snap=${module}-${date}

cvs -Q rtag -F snapshot-$date $module

rm -rf $snap
## Checkout the $module into a directory named $snap
#cvs checkout -d $snap -r snapshot-$date $module
#tar -f - -co $snap | gzip -9v -c > $snap.tar.gz

make snapshot

#find $snap \( -name CVS -prune \) -o \( -type f -print \) |
#xargs md5sum | gzip -9v -c > $snap.md5sum.gz

rm -rf $snap &

mv -f $snap.tar.gz $dir
