#!/bin/sh

# Copy a dist file to the ftp server
# if shell variable OLD is set to a version string, also copy a diff file.

SOURCEDIR=$HOME/gnu/releases

DESTHOST=alpha.gnu.ai.mit.edu
DESTDIR='~ftp/gnu/gnustep'

# Load version variables
. Version

DISTFILE=gstep-base-${VERSION}.tar.gz

echo Uploading $DISTFILE to ${DESTHOST}:${DESTDIR}
cat ${SOURCEDIR}/${DISTFILE} \
	 | rsh $DESTHOST \
	  "(cd $DESTDIR; \
	    cat >| ${DISTFILE})"


if [ $OLD ] ; then
  # Also upload the diff file

  DIFFFILE=gstep-base-${OLD}-${VERSION}.diff.gz

  if [ ! -e ${SOURCEDIR}/${DIFFFILE} ] ; then
    echo File ${SOURCEDIR}/${DIFFFILE} not found.
    exit -1
  fi

  echo Uploading ${DIFFFILE} to ${DESTHOST}:${DESTDIR}

  cat ${SOURCEDIR}/${DIFFFILE} \
	 | rsh $DESTHOST \
	  "(cd $DESTDIR; \
	    cat >| ${DIFFFILE})"

fi
