
ifeq ($(FOUNDATION_LIB),apple)

# Things to do before compiling
before-all::
	rm -f GNUstepBase
	ln -s ../../Headers/GNUstepBase GNUstepBase

# Things to do after cleaning
after-clean::
	rm -f GNUstepBase

endif

