
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = capture respond keepalive

capture_OBJC_FILES = capture.m
capture_NEEDS_GUI = NO

respond_OBJC_FILES = respond.m
respond_NEEDS_GUI = NO

keepalive_OBJC_FILES = keepalive.m
keepalive_NEEDS_GUI = NO

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

