
include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = TestBundle

TestBundle_OBJC_FILES = TestBundle.m
TestBundle_RESOURCE_FILES = NonLocalRes.txt
TestBundle_LANGUAGES = English French de
TestBundle_LOCALIZED_RESOURCE_FILES = TextRes.txt
TestBundle_NEEDS_GUI = NO

include $(GNUSTEP_MAKEFILES)/bundle.make

check::	all
