
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = doubleNSLock doubleNSConditionLock

doubleNSLock_OBJC_FILES = doubleNSLock.m
doubleNSLock_NEEDS_GUI = NO

doubleNSConditionLock_OBJC_FILES = doubleNSConditionLock.m
doubleNSConditionLock_NEEDS_GUI = NO

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

