include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/common.make

# The application to be compiled
TOOL_NAME = gdomap

# The source files to be compiled
gdomap_C_FILES = gdomap.c

-include Makefile.preamble

include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/tool.make

-include Makefile.postamble
