/**
   NSKVOSwizzling.m

   Copyright (C) 2024 Free Software Foundation, Inc.

   Written by: Hugo Melder <hugo@algoriddim.com>
   Date: June 2024

   Based on WinObjC KVO tests by Microsoft Corporation.

   This file is part of GNUStep-base

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   If you are interested in a warranty or support for this source code,
   contact Scott Christley <scottc@net-community.com> for more information.

   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110 USA.
*/
/**
  Copyright (c) Microsoft. All rights reserved.

  This code is licensed under the MIT License (MIT).

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

/* Key Value Observing setter swizzling.  There are two backends, selected on
 * the runtime: the libobjc2 path adds notifying methods per object with
 * object_addMethod_np; other runtimes install them on a per-class
 * NSKVONotifying_<Class> subclass and switch the observed instance's isa.
 */

#import "common.h"
#import "NSKVOInternal.h"
#import "GSPThread.h"
#import <objc/runtime.h>
#import <Foundation/Foundation.h>

#ifdef WIN32
#define alloca(x) _alloca(x)
#endif

#if defined(__OBJC2__) && !defined(NSKVO_FORCE_PORTABLE)
/* ==================================================================== *
 *  libobjc2 backend: per-object method addition (object_addMethod_np).  *
 * ==================================================================== */

#import <objc/encoding.h>
#import "NSKVOTypeEncodingCases.h"

/* These are defined by the ABI and the runtime. */
#define ABI_SUPER(obj) (((Class **) obj)[0][1])
#define ABI_ISA(obj) (((Class *) obj)[0])

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-objc-pointer-introspection"
// Small objects, as defined by libobjc2, are tagged pointers. Instead of being
// heap-allocated, the object is stored in the sizeof(id) -
// OBJC_SMALL_OBJECT_BITS bits of the "pointer" itself.
static inline bool
isSmallObject_np(id object)
{
  return ((((uintptr_t) object) & OBJC_SMALL_OBJECT_MASK) != 0);
}
#pragma clang diagnostic pop

static void
NSKVO$setObject$forKey$(id self, SEL _cmd, id object, NSString *key);
static void
NSKVO$removeObjectForKey$(id self, SEL _cmd, NSString *key);
static void
NSKVO$nilIMP(id self, SEL _cmd)
{}

static void
_NSKVOEnsureObjectIsKVOAware(id object)
{
  // We have to use ABI_ISA here, because object_getClass will skip the secret
  // hidden subclass.
  if (class_respondsToSelector(ABI_ISA(object), @selector(_isKVOAware)))
    {
      // The presence of _isKVOAware signals that we have already mangled this
      // object.
      return;
    }

  /*
   A crucial design decision was made here: because object_getClass() skips
   autogenerated subclasses, the likes of which are used for associated objects,
   the KVO machinery (if implemented using manual subclassing) would delete all
   associated objects on an observed instance. That was deemed unacceptable.

   Likewise, this implementation is not free of issues:
   - The _np methods are nonportable.
   - Anyone using class_getMethodImplementation(object_getClass(...), ...) will
   receive the original IMP for any overridden method.
   - We have to manually load isa to get at the secret subclass (thus the use of
   ABI_ISA/ABI_SUPER.)
   - It is dependent upon a libobjc2 implementation detail:
       object_addMethod_np creates a hidden subclass for the object's class (one
   per object!)
  */

  object_addMethod_np(object, @selector(setObject:forKey:),
    (IMP)(NSKVO$setObject$forKey$), "v@:@@");
  object_addMethod_np(object, @selector(removeObjectForKey:),
    (IMP)(NSKVO$removeObjectForKey$), "v@:@");
  object_addMethod_np(object, @selector(_isKVOAware),
    (IMP)(NSKVO$nilIMP), "v@:");
}

#pragma region Method Implementations
// Selector mappings: the class-level mapping from a selector (setX:) to the KVC
// key ("x") to which it corresponds. This is necessary because both "X" and "x"
// map to setX:, but we need to be cognizant of precisely which it was for any
// given observee. The sole reason we can get away with keeping selector<->key
// mappings on the class is that, through the lifetime of said class, it can
// never lose selectors. This mapping will be pertinent to every instance of the
// class.
static inline NSMapTable *
_selectorMappingsForObject(id object)
{
  static char s_selMapKey;
  Class       cls;

  // here we explicitly want the public
  // (non-hidden) class associated with the object.
  cls = object_getClass(object);

  @synchronized(cls)
  {
    NSMapTable *selMappings
      = (NSMapTable *) objc_getAssociatedObject(cls, &s_selMapKey);
    if (!selMappings)
      {
        selMappings = [NSMapTable
          mapTableWithKeyOptions: NSPointerFunctionsOpaqueMemory
                                | NSPointerFunctionsOpaquePersonality
                    valueOptions: NSPointerFunctionsStrongMemory
				| NSPointerFunctionsObjectPersonality];
        objc_setAssociatedObject(cls, &s_selMapKey, (id) selMappings,
	  OBJC_ASSOCIATION_RETAIN);
      }
    return selMappings;
  }
}

static inline NSString *
_keyForSelector(id object, SEL selector)
{
  return (NSString *) NSMapGet(_selectorMappingsForObject(object),
    sel_getName(selector));
}

static inline void
_associateSelectorWithKey(id object, SEL selector, NSString *key)
{
  /* this must be insertIfAbsent. otherwise, when calling a setter that itself
   * causes observers to be added/removed on this key, this would call this
   * method and overwrite the association selector->key with an identical key
   * but another object. unfortunately, this would mean that the
   * notifyingSetImpl below would then have a dead ```key``` pointer once it
   * came time to call didChangeValueForKey (because apparently ARC doesn't take
   * care of this properly)
   */
  NSMapInsertIfAbsent(_selectorMappingsForObject(object),
    sel_getName(selector), key);
}

static void
notifyingVariadicSetImpl(id self, SEL _cmd, ...)
{
  NSString *key = _keyForSelector(self, _cmd);

  /* [Source: NSInvocation.mm]
   * This attempts to flatten the method's arguments (as determined by its type
   * encoding) from the stack into a buffer. That buffer is then emitted back
   * onto the stack for the imp callthrough. This only works if we assume that
   * our calling convention passes variadics and non-variadics in the same way:
   * on the stack. For our two supported platforms, this seems to hold true.
   */
  NSMethodSignature *sig = [self methodSignatureForSelector: _cmd];
  size_t             argSz = objc_sizeof_type([sig getArgumentTypeAtIndex: 2]);
  size_t             nStackArgs = argSz / sizeof(uintptr_t);
  uintptr_t *raw = (uintptr_t *) (calloc(sizeof(uintptr_t), nStackArgs));
  va_list   ap;

  va_start(ap, _cmd);
  for (uintptr_t i = 0; i < nStackArgs; ++i)
    {
      raw[i] = va_arg(ap, uintptr_t);
    }
  va_end(ap);

  [self willChangeValueForKey: key];
  {
    struct objc_super super = {self, ABI_SUPER(self)};
    IMP imp = (id(*)(id, SEL, ...)) objc_msg_lookup_super(&super, _cmd);

    // VSO 5955259; NSInvocation informs this implementation and this will need
    // to be cleaned up when NSInvocation is.
    switch (nStackArgs)
      {
	case 1:
	  imp(self, _cmd, raw[0]);
	  break;
	case 2:
	  imp(self, _cmd, raw[0], raw[1]);
	  break;
	case 3:
	  imp(self, _cmd, raw[0], raw[1], raw[2]);
	  break;
	case 4:
	  imp(self, _cmd, raw[0], raw[1], raw[2], raw[3]);
	  break;
	case 5:
	  imp(self, _cmd, raw[0], raw[1], raw[2], raw[3], raw[4]);
	  break;
	case 6:
	  imp(self, _cmd, raw[0], raw[1], raw[2], raw[3], raw[4], raw[5]);
	  break;
	default:
	  NSLog(@"Can't override setter with more than 6"
	    @" sizeof(long int) stack arguments.");
	  return;
      }
  }
  [self didChangeValueForKey: key];

  free(raw);
}

typedef void (*insertObjectAtIndexIMP)(id, SEL, id, NSUInteger);
typedef void (*removeObjectAtIndexIMP)(id, SEL, NSUInteger);
typedef void (*insertAtIndexesIMP)(id, SEL, id, NSIndexSet *);
typedef void (*removeAtIndexesIMP)(id, SEL, NSIndexSet *);
typedef void (*replaceAtIndexesIMP)(id, SEL, NSIndexSet *, NSArray *);
typedef void (*setObjectForKeyIMP)(id, SEL, id, NSString *);
typedef void (*removeObjectForKeyIMP)(id, SEL, NSString *);
typedef void (*replaceObjectAtIndexWithObjectIMP)(id, SEL, NSUInteger, id);

static void
NSKVONotifying$insertObject$inXxxAtIndex$(id self, SEL _cmd, id object,
  NSUInteger index)
{
  NSString   *key = _keyForSelector(self, _cmd);
  NSIndexSet *indexes = [NSIndexSet indexSetWithIndex: index];

  [self willChange: NSKeyValueChangeInsertion
   valuesAtIndexes: indexes
            forKey: key];
  {
    struct objc_super      super = {self, ABI_SUPER(self)};
    insertObjectAtIndexIMP imp = (void (*)(id, SEL, id, NSUInteger))
      objc_msg_lookup_super(&super, _cmd);
    imp(self, _cmd, object, index);
  }
  [self didChange: NSKeyValueChangeInsertion
  valuesAtIndexes: indexes
	   forKey: key];
}

static void
NSKVONotifying$insertXxx$atIndexes$(id self, SEL _cmd, id object,
  NSIndexSet *indexes)
{
  NSString *key = _keyForSelector(self, _cmd);

  [self willChange: NSKeyValueChangeInsertion
   valuesAtIndexes: indexes
            forKey: key];
  {
    struct objc_super  super = {self, ABI_SUPER(self)};
    insertAtIndexesIMP imp = (void (*)(id, SEL, id, NSIndexSet *))
      objc_msg_lookup_super(&super, _cmd);
    imp(self, _cmd, object, indexes);
  }
  [self didChange: NSKeyValueChangeInsertion
  valuesAtIndexes: indexes
	   forKey: key];
}

static void
NSKVONotifying$removeObjectFromXxxAtIndex$(id self, SEL _cmd, NSUInteger index)
{
  NSString   *key = _keyForSelector(self, _cmd);
  NSIndexSet *indexes = [NSIndexSet indexSetWithIndex: index];

  [self willChange: NSKeyValueChangeRemoval
   valuesAtIndexes: indexes
	    forKey: key];
  {
    struct objc_super      super = {self, ABI_SUPER(self)};
    removeObjectAtIndexIMP imp = (void (*)(id, SEL, NSUInteger))
      objc_msg_lookup_super(&super, _cmd);
    imp(self, _cmd, index);
  }
  [self didChange: NSKeyValueChangeRemoval
  valuesAtIndexes: indexes
           forKey: key];
}

static void
NSKVONotifying$removeXxxAtIndexes$(id self, SEL _cmd, NSIndexSet *indexes)
{
  NSString *key = _keyForSelector(self, _cmd);

  [self willChange: NSKeyValueChangeRemoval
   valuesAtIndexes: indexes
  	    forKey: key];
  {
    struct objc_super  super = {self, ABI_SUPER(self)};
    removeAtIndexesIMP imp = (void (*)(id, SEL, NSIndexSet *))
      objc_msg_lookup_super(&super, _cmd);
    imp(self, _cmd, indexes);
  }
  [self didChange: NSKeyValueChangeRemoval
  valuesAtIndexes: indexes
	   forKey: key];
}

static void
NSKVONotifying$replaceObjectInXxxAtIndex$withObject$(id self, SEL _cmd,
  NSUInteger index, id object)
{
  NSString   *key = _keyForSelector(self, _cmd);
  NSIndexSet *indexes = [NSIndexSet indexSetWithIndex: index];

  [self willChange: NSKeyValueChangeReplacement
    valuesAtIndexes: indexes
             forKey: key];
  {
    struct objc_super                 super = {self, ABI_SUPER(self)};
    replaceObjectAtIndexWithObjectIMP imp = (void (*)(id, SEL, NSUInteger, id))
      objc_msg_lookup_super(&super, _cmd);
    imp(self, _cmd, index, object);
  }
  [self didChange: NSKeyValueChangeReplacement
  valuesAtIndexes: indexes
	   forKey: key];
}

static void
NSKVONotifying$replaceXxxAtIndexes$withXxx$(id self, SEL _cmd,
  NSIndexSet *indexes, NSArray *objects)
{
  NSString *key = _keyForSelector(self, _cmd);

  [self willChange: NSKeyValueChangeReplacement
   valuesAtIndexes: indexes
            forKey: key];
  {
    struct objc_super   super = {self, ABI_SUPER(self)};
    replaceAtIndexesIMP imp = (void (*)(id, SEL, NSIndexSet *, NSArray *))
      objc_msg_lookup_super(&super, _cmd);
    imp(self, _cmd, indexes, objects);
  }
  [self didChange: NSKeyValueChangeReplacement
  valuesAtIndexes: indexes
           forKey: key];
}

#define GENERATE_NSKVOSetDispatch_IMPL(Kind)                                   \
  static inline void _NSKVOSetDispatch_##Kind(id self, SEL _cmd, NSSet *set)   \
  {                                                                            \
    NSString *key = _keyForSelector(self, _cmd);                               \
    [self willChangeValueForKey: key withSetMutation: Kind usingObjects: set]; \
    {									       \
    struct objc_super super = {self, ABI_SUPER(self)};                         \
    void (*imp)(id, SEL, NSSet *)                                              \
      = (void (*)(id, SEL, NSSet *)) objc_msg_lookup_super(&super, _cmd);      \
    imp(self, _cmd, set);                                                      \
    }									       \
    [self didChangeValueForKey: key withSetMutation: Kind usingObjects: set];  \
  }

#define GENERATE_NSKVOSetDispatchIndividual_IMPL(Kind)                         \
  static inline void _NSKVOSetDispatchIndividual_##Kind(id self, SEL _cmd,     \
    id obj)                						       \
  {                                                                            \
    NSSet    *set = [NSSet setWithObject: obj];                                \
    NSString *key = _keyForSelector(self, _cmd);                               \
    [self willChangeValueForKey: key withSetMutation: Kind usingObjects: set]; \
    {									       \
    struct objc_super super = {self, ABI_SUPER(self)};                         \
    void (*imp)(id, SEL, id)                                                   \
      = (void (*)(id, SEL, id)) objc_msg_lookup_super(&super, _cmd);           \
    imp(self, _cmd, obj);                                                      \
    }									       \
    [self didChangeValueForKey: key withSetMutation: Kind usingObjects: set];  \
  }

GENERATE_NSKVOSetDispatchIndividual_IMPL(NSKeyValueUnionSetMutation);
GENERATE_NSKVOSetDispatchIndividual_IMPL(NSKeyValueMinusSetMutation);
//GENERATE_NSKVOSetDispatchIndividual_IMPL(NSKeyValueIntersectSetMutation);

GENERATE_NSKVOSetDispatch_IMPL(NSKeyValueUnionSetMutation);
GENERATE_NSKVOSetDispatch_IMPL(NSKeyValueMinusSetMutation);
GENERATE_NSKVOSetDispatch_IMPL(NSKeyValueIntersectSetMutation);

// - (void)setObject: (id)object forKey: (NSString*)key
static void
NSKVO$setObject$forKey$(id self, SEL _cmd, id object, NSString *key)
{
  [self willChangeValueForKey: key];
{
  struct objc_super  super = {self, ABI_SUPER(self)};
  setObjectForKeyIMP imp;

  imp = (void (*)(id, SEL, id, NSString *)) objc_msg_lookup_super(&super, _cmd);
  imp(self, _cmd, object, key);
}
  [self didChangeValueForKey: key];
}

// - (void)removeObjectForKey: (NSString*)key
static void
NSKVO$removeObjectForKey$(id self, SEL _cmd, NSString *key)
{
  [self willChangeValueForKey: key];
{
  struct objc_super     super = {self, ABI_SUPER(self)};
  removeObjectForKeyIMP imp;

  imp = (void (*)(id, SEL, NSString *)) objc_msg_lookup_super(&super, _cmd);
  imp(self, _cmd, key);
}
  [self didChangeValueForKey: key];
}
#pragma endregion

#define GENERATE_NOTIFYING_SET_IMPL(funcName, type)                            \
  static void funcName(id self, SEL _cmd, type val)                            \
  {                                                                            \
    struct objc_super super = {self, ABI_SUPER(self)};                         \
    void (*imp)(id, SEL, type)                                                 \
      = (void (*)(id, SEL, type)) objc_msg_lookup_super(&super, _cmd);         \
    if (nil == [self observationInfo])                                         \
      {                                                                        \
        imp(self, _cmd, val);                                                  \
        return;                                                                \
      }                                                                        \
    {                                                                          \
      NSString *key = _keyForSelector(self, _cmd);                             \
      [self willChangeValueForKey: key];                                       \
      imp(self, _cmd, val);                                                    \
      [self didChangeValueForKey: key];                                        \
    }                                                                          \
  }

GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplDouble, double);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplFloat, float);

GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplChar, signed char);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplInt, int);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplShort, short);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplLong, long);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplLongLong, long long);

GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplUnsignedChar, unsigned char);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplUnsignedInt, unsigned int);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplUnsignedShort, unsigned short);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplUnsignedLong, unsigned long);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplUnsignedLongLong,
  unsigned long long);

// GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplBool, bool);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplObject, id);
GENERATE_NOTIFYING_SET_IMPL(notifyingSetImplPointer, void *);

#define KVO_SET_IMPL_CASE(type, name, capitalizedName, encodingChar)           \
    case encodingChar: {                                                       \
      newImpl = (IMP) (&notifyingSetImpl##capitalizedName);                    \
      break;                                                                   \
    }

static SEL
KVCSetterForPropertyName(NSObject *self, const char *key)
{
  SEL    sel = nil;
  size_t len = strlen(key);
  // For the key "example", we must construct the following buffer:
  // _ _ _ _ x a m p l e _ \0
  // and fill it with the following characters:
  // s e t E x a m p l e : \0
  char *buf = (char *) alloca(3 + len + 2);
  memcpy(buf + 4, key + 1, len);
  buf[0] = 's';
  buf[1] = 'e';
  buf[2] = 't';
  buf[3] = toupper(key[0]);
  buf[3 + len] = ':';
  buf[3 + len + 1] = '\0';
  sel = sel_getUid(buf);
  if ([self respondsToSelector: sel])
    {
      return sel;
    }

  return nil;
}

// invariant: rawKey has already been capitalized
static inline void
_NSKVOEnsureSimpleKeyWillNotify(id object, NSString *key, const char *rawKey)
{
  Method		originalMethod;
  const char		*valueType;
  const char		*types;
  NSMethodSignature	*sig;
  SEL 			sel;
  IMP         		newImpl = NULL;
  
  sel = KVCSetterForPropertyName(object, rawKey);
  originalMethod = class_getInstanceMethod(object_getClass(object), sel);
  types = method_getTypeEncoding(originalMethod);
  if (!types)
    {
      return;
    }

  sig = [NSMethodSignature signatureWithObjCTypes: types];
  valueType = [sig getArgumentTypeAtIndex: 2];

  switch (valueType[0])
    {
      OBJC_APPLY_ALL_TYPE_ENCODINGS(KVO_SET_IMPL_CASE);
    case '{':
      case '[': {
        size_t valueSize = objc_sizeof_type(valueType);
        if (valueSize > 6 * sizeof(uintptr_t))
          {
            [NSException raise: NSInvalidArgumentException
                        format: @"Class %s key %@ has a value size of %u bytes"
	      @", and cannot currently be KVO compliant.",
	      class_getName(object_getClass(object)), key,
	      (unsigned int) (valueSize)];
          }
        newImpl = (IMP) (&notifyingVariadicSetImpl);
        break;
      }
    default:
      [NSException raise: NSInvalidArgumentException
                  format: @"Class %s is not KVO compliant for key %@.",
	class_getName(object_getClass(object)), key];
      return;
    }

  _associateSelectorWithKey(object, sel, key);
  object_addMethod_np(object, sel, newImpl, types);
}

static void
replaceAndAssociateWithKey(id object, SEL sel, NSString *key, IMP imp)
{
  if ([object respondsToSelector: sel])
    {
      const char *selName = sel_getName(sel);
      Method method = class_getInstanceMethod(object_getClass(object), sel);
      if (!method)
        {
          NSWarnLog(@"NSObject (NSKeyValueObservation): Unable to find method "
	    @"for %s on class %s; perhaps it is a forward?",
	    selName, object_getClassName(object));
          return;
        }

      _associateSelectorWithKey(object, sel, key);
      object_replaceMethod_np(object, sel, imp, method_getTypeEncoding(method));
    }
}

static SEL
formatSelector(NSString *format, ...)
{
  NSString	*s;
  SEL 		sel;
  va_list 	ap;

  va_start(ap, format);
  s = [[NSString alloc] initWithFormat: format arguments: ap];
  sel = NSSelectorFromString([s autorelease]);
  va_end(ap);
  return sel;
}

// invariant: rawKey has already been capitalized
static inline void
_NSKVOEnsureOrderedCollectionWillNotify(id object, NSString *key,
  const char *rawKey)
{
  SEL insertOne = formatSelector(@"insertObject:in%sAtIndex:", rawKey);
  SEL insertMany = formatSelector(@"insert%s:atIndexes:", rawKey);

  if ([object respondsToSelector: insertOne]
    || [object respondsToSelector: insertMany])
    {
      replaceAndAssociateWithKey(object, insertOne, key,
        (IMP)NSKVONotifying$insertObject$inXxxAtIndex$);
      replaceAndAssociateWithKey(object, insertMany, key,
	(IMP)NSKVONotifying$insertXxx$atIndexes$);
      replaceAndAssociateWithKey(
        object, formatSelector(@"removeObjectFrom%sAtIndex:", rawKey), key,
        (IMP)NSKVONotifying$removeObjectFromXxxAtIndex$);
      replaceAndAssociateWithKey(object,
        formatSelector(@"remove%sAtIndexes:", rawKey),
        key, (IMP)NSKVONotifying$removeXxxAtIndexes$);
      replaceAndAssociateWithKey(
        object, formatSelector(@"replaceObjectIn%sAtIndex:withObject:", rawKey),
        key, (IMP)NSKVONotifying$replaceObjectInXxxAtIndex$withObject$);
      replaceAndAssociateWithKey(
        object, formatSelector(@"replace%sAtIndexes:with%s:", rawKey, rawKey),
        key, (IMP)NSKVONotifying$replaceXxxAtIndexes$withXxx$);
    }
}

// invariant: rawKey has already been capitalized
static inline void
_NSKVOEnsureUnorderedCollectionWillNotify(id object, NSString *key,
  const char *rawKey)
{
  SEL addOne = formatSelector(@"add%sObject:", rawKey);
  SEL addMany = formatSelector(@"add%s:", rawKey);
  SEL removeOne = formatSelector(@"remove%sObject:", rawKey);
  SEL removeMany = formatSelector(@"remove%s:", rawKey);

  if (([object respondsToSelector: addOne]
    || [object respondsToSelector: addMany])
    && ([object respondsToSelector: removeOne]
      || [object respondsToSelector: removeMany]))
    {
      replaceAndAssociateWithKey(
        object, addOne, key,
        (IMP)_NSKVOSetDispatchIndividual_NSKeyValueUnionSetMutation);
      replaceAndAssociateWithKey(
        object, addMany, key,
        (IMP)_NSKVOSetDispatch_NSKeyValueUnionSetMutation);
      replaceAndAssociateWithKey(
        object, removeOne, key,
        (IMP)_NSKVOSetDispatchIndividual_NSKeyValueMinusSetMutation);
      replaceAndAssociateWithKey(
        object, removeMany, key,
        (IMP)_NSKVOSetDispatch_NSKeyValueMinusSetMutation);
      replaceAndAssociateWithKey(
        object, formatSelector(@"intersect%s:", rawKey), key,
        (IMP)_NSKVOSetDispatch_NSKeyValueIntersectSetMutation);
    }
}

static char *
mutableBufferFromString(NSString *string)
{
  NSUInteger	lengthInBytes = [string length] + 1;
  char      	*rawKey = (char *) malloc(lengthInBytes);

  [string getCString: rawKey
           maxLength: lengthInBytes
            encoding: NSASCIIStringEncoding];
  return rawKey;
}

// NSKVOEnsureKeyWillNotify is the main entrypoint into the swizzling code.
void
_NSKVOEnsureKeyWillNotify(id object, NSString *key)
{
  char *rawKey;
  Class cls;
  Class underlyingCls;

  // Since we cannot replace the isa of tagged pointer objects, we can't swizzle
  // them.
  if (isSmallObject_np(object))
    {
      return;
    }

  cls = [object class];
  underlyingCls = [object _underlyingClass];
  // If cls differs from underlyingCls, object is actually a proxy.
  // Retrieve the underlying object with KVC.
  if (cls != underlyingCls)
  {
    object = [object valueForKey: @"self"];
  }

  // A class is allowed to decline automatic swizzling for any/all of its keys.
  if (![underlyingCls automaticallyNotifiesObserversForKey: key])
    {
      return;
    }

  rawKey = mutableBufferFromString(key);
  rawKey[0] = toupper(rawKey[0]);

  @synchronized(object)
  {
    _NSKVOEnsureObjectIsKVOAware(object);
    _NSKVOEnsureSimpleKeyWillNotify(object, key, rawKey);
    _NSKVOEnsureOrderedCollectionWillNotify(object, key, rawKey);
    _NSKVOEnsureUnorderedCollectionWillNotify(object, key, rawKey);
  }

  free(rawKey);
}

#else
/* ==================================================================== *
 *  Portable backend: per-class NSKVONotifying_<Class> subclass.  Works  *
 *  on any runtime that provides objc_allocateClassPair/object_setClass  *
 *  (i.e. without libobjc2's per-object object_addMethod_np).            *
 * ==================================================================== */

#import "NSKVOTypeEncodingCases.h"

/* Per public class: the notifying subclass, plus (keyed by selector name) the
 * KVC key and the ORIGINAL setter IMP.  The original IMP is cached at install
 * time.  Selectors are keyed by NAME: on the GNU runtime they are typed, so
 * two selectors with the same name need not be the same pointer.
 */
@interface _NSKVOSwizzledClass : NSObject
{
@public
  Class		subclass;
  NSMapTable	*keyForSelector;
  NSMapTable	*impForSelector;
}
@end

/* One recursive lock guards all swizzle setup below.  The setup entry points
 * nest (ensure -> info-for-class -> install-override), so it must be recursive.
 * @synchronized is avoided because it requires Objective-C exceptions, which
 * the GNU runtime does not enable on Windows. */
static gs_mutex_t kvoSwizzleLock;

@implementation _NSKVOSwizzledClass
+ (void) load
{
  GS_MUTEX_INIT_RECURSIVE(kvoSwizzleLock);
}
@end

/* -class is overridden on the subclass so the observed object still reports
 * its public class. */
static Class
_NSKVONotifyingClass(id self, SEL _cmd)
{
  return class_getSuperclass(object_getClass(self));
}

/* The public class of an object, seeing through a notifying subclass. */
static Class
_NSKVOPublicClass(id object)
{
  Class c = object_getClass(object);
  if (class_getInstanceMethod(c, @selector(class)) != NULL
    && class_getMethodImplementation(c, @selector(class)) == (IMP) _NSKVONotifyingClass)
    return class_getSuperclass(c);
  return c;
}

static _NSKVOSwizzledClass *
_NSKVOInfoForClass(Class cls)
{
  static void	*assocKey = &assocKey;
  _NSKVOSwizzledClass *info;

  GS_MUTEX_LOCK(kvoSwizzleLock);
  {
    info = (_NSKVOSwizzledClass *) objc_getAssociatedObject(cls, &assocKey);
    if (nil == info)
      {
	char name[256];

	info = [_NSKVOSwizzledClass new];
	snprintf(name, sizeof(name), "NSKVONotifying_%s", class_getName(cls));
	info->subclass = objc_allocateClassPair(cls, name, 0);
	info->keyForSelector = [[NSMapTable alloc] initWithKeyOptions:
	  NSPointerFunctionsCStringPersonality | NSPointerFunctionsOpaqueMemory
	  valueOptions: NSPointerFunctionsStrongMemory
	  | NSPointerFunctionsObjectPersonality capacity: 4];
	info->impForSelector = [[NSMapTable alloc] initWithKeyOptions:
	  NSPointerFunctionsCStringPersonality | NSPointerFunctionsOpaqueMemory
	  valueOptions: NSPointerFunctionsOpaqueMemory
	  | NSPointerFunctionsOpaquePersonality capacity: 4];
	class_addMethod(info->subclass, @selector(class),
	  (IMP) _NSKVONotifyingClass, "#@:");
	objc_registerClassPair(info->subclass);
	objc_setAssociatedObject(cls, &assocKey, info, OBJC_ASSOCIATION_RETAIN);
      }
  }
  GS_MUTEX_UNLOCK(kvoSwizzleLock);
  return info;
}

/* Look up the KVC key and cached original IMP for a notifying setter call. */
static inline void
_NSKVOPortableLookup(id self, SEL _cmd, NSString **key, IMP *orig)
{
  _NSKVOSwizzledClass *info
    = _NSKVOInfoForClass(class_getSuperclass(object_getClass(self)));
  const char *name = sel_getName(_cmd);

  *key = (NSString *) NSMapGet(info->keyForSelector, name);
  *orig = (IMP) NSMapGet(info->impForSelector, name);
}

#define GENERATE_PORTABLE_SET_IMPL(funcName, type)                             \
  static void funcName(id self, SEL _cmd, type val)                            \
  {                                                                            \
    NSString *key;                                                             \
    IMP       orig;                                                            \
    _NSKVOPortableLookup(self, _cmd, &key, &orig);                             \
    [self willChangeValueForKey: key];                                         \
    ((void (*)(id, SEL, type)) orig)(self, _cmd, val);                         \
    [self didChangeValueForKey: key];                                          \
  }

GENERATE_PORTABLE_SET_IMPL(portableSetDouble, double);
GENERATE_PORTABLE_SET_IMPL(portableSetFloat, float);
GENERATE_PORTABLE_SET_IMPL(portableSetChar, signed char);
GENERATE_PORTABLE_SET_IMPL(portableSetInt, int);
GENERATE_PORTABLE_SET_IMPL(portableSetShort, short);
GENERATE_PORTABLE_SET_IMPL(portableSetLong, long);
GENERATE_PORTABLE_SET_IMPL(portableSetLongLong, long long);
GENERATE_PORTABLE_SET_IMPL(portableSetUnsignedChar, unsigned char);
GENERATE_PORTABLE_SET_IMPL(portableSetUnsignedInt, unsigned int);
GENERATE_PORTABLE_SET_IMPL(portableSetUnsignedShort, unsigned short);
GENERATE_PORTABLE_SET_IMPL(portableSetUnsignedLong, unsigned long);
GENERATE_PORTABLE_SET_IMPL(portableSetUnsignedLongLong, unsigned long long);
GENERATE_PORTABLE_SET_IMPL(portableSetObject, id);
GENERATE_PORTABLE_SET_IMPL(portableSetPointer, void *);

#define KVO_SET_IMPL_CASE(type, name, capitalizedName, encodingChar)           \
    case encodingChar: {                                                       \
      newImpl = (IMP) (&portableSet##capitalizedName);                         \
      break;                                                                   \
    }

/* Setters whose value is a structure or array are passed on the stack.  We
 * cannot know the exact prototype, so flatten the words the caller pushed and
 * re-emit them to the original implementation.  This assumes variadic and
 * non-variadic calls pass such arguments the same way, which holds on the
 * platforms we support; the value size is capped (see below) accordingly. */
static void
portableVariadicSetImpl(id self, SEL _cmd, ...)
{
  NSString		*key;
  IMP			orig;
  NSMethodSignature	*sig = [self methodSignatureForSelector: _cmd];
  size_t		argSz = objc_sizeof_type([sig getArgumentTypeAtIndex: 2]);
  size_t		nStackArgs = argSz / sizeof(uintptr_t);
  uintptr_t		*raw = (uintptr_t *) calloc(sizeof(uintptr_t), nStackArgs);
  va_list		ap;
  uintptr_t		i;

  _NSKVOPortableLookup(self, _cmd, &key, &orig);

  va_start(ap, _cmd);
  for (i = 0; i < nStackArgs; ++i)
    {
      raw[i] = va_arg(ap, uintptr_t);
    }
  va_end(ap);

  [self willChangeValueForKey: key];
  switch (nStackArgs)
    {
      case 1:
	((void (*)(id, SEL, uintptr_t)) orig)(self, _cmd, raw[0]);
	break;
      case 2:
	((void (*)(id, SEL, uintptr_t, uintptr_t)) orig)
	  (self, _cmd, raw[0], raw[1]);
	break;
      case 3:
	((void (*)(id, SEL, uintptr_t, uintptr_t, uintptr_t)) orig)
	  (self, _cmd, raw[0], raw[1], raw[2]);
	break;
      case 4:
	((void (*)(id, SEL, uintptr_t, uintptr_t, uintptr_t, uintptr_t)) orig)
	  (self, _cmd, raw[0], raw[1], raw[2], raw[3]);
	break;
      case 5:
	((void (*)(id, SEL, uintptr_t, uintptr_t, uintptr_t, uintptr_t,
	  uintptr_t)) orig)(self, _cmd, raw[0], raw[1], raw[2], raw[3], raw[4]);
	break;
      case 6:
	((void (*)(id, SEL, uintptr_t, uintptr_t, uintptr_t, uintptr_t,
	  uintptr_t, uintptr_t)) orig)
	  (self, _cmd, raw[0], raw[1], raw[2], raw[3], raw[4], raw[5]);
	break;
      default:
	NSLog(@"Can't override setter with more than 6"
	  @" sizeof(long int) stack arguments.");
	free(raw);
	return;
    }
  [self didChangeValueForKey: key];

  free(raw);
}

static SEL
KVCSetterForPropertyName(NSObject *self, const char *key)
{
  SEL    sel;
  size_t len = strlen(key);
  char  *buf = (char *) alloca(3 + len + 2);

  memcpy(buf + 4, key + 1, len);
  buf[0] = 's'; buf[1] = 'e'; buf[2] = 't';
  buf[3] = toupper(key[0]);
  buf[3 + len] = ':';
  buf[3 + len + 1] = '\0';
  sel = sel_getUid(buf);
  return [self respondsToSelector: sel] ? sel : (SEL) 0;
}

static char *
mutableBufferFromString(NSString *string)
{
  NSUInteger	lengthInBytes = [string length] + 1;
  char		*rawKey = (char *) malloc(lengthInBytes);

  [string getCString: rawKey
	   maxLength: lengthInBytes
	    encoding: NSASCIIStringEncoding];
  return rawKey;
}

/* Indexed (ordered to-many) mutation notifiers. */
static void
portableInsertObjectAtIndex(id self, SEL _cmd, id object, NSUInteger index)
{
  NSString	*key;
  IMP		orig;
  NSIndexSet	*indexes = [NSIndexSet indexSetWithIndex: index];

  _NSKVOPortableLookup(self, _cmd, &key, &orig);
  [self willChange: NSKeyValueChangeInsertion valuesAtIndexes: indexes forKey: key];
  ((void (*)(id, SEL, id, NSUInteger)) orig)(self, _cmd, object, index);
  [self didChange: NSKeyValueChangeInsertion valuesAtIndexes: indexes forKey: key];
}
static void
portableInsertAtIndexes(id self, SEL _cmd, id objects, NSIndexSet *indexes)
{
  NSString	*key;
  IMP		orig;

  _NSKVOPortableLookup(self, _cmd, &key, &orig);
  [self willChange: NSKeyValueChangeInsertion valuesAtIndexes: indexes forKey: key];
  ((void (*)(id, SEL, id, NSIndexSet *)) orig)(self, _cmd, objects, indexes);
  [self didChange: NSKeyValueChangeInsertion valuesAtIndexes: indexes forKey: key];
}
static void
portableRemoveObjectAtIndex(id self, SEL _cmd, NSUInteger index)
{
  NSString	*key;
  IMP		orig;
  NSIndexSet	*indexes = [NSIndexSet indexSetWithIndex: index];

  _NSKVOPortableLookup(self, _cmd, &key, &orig);
  [self willChange: NSKeyValueChangeRemoval valuesAtIndexes: indexes forKey: key];
  ((void (*)(id, SEL, NSUInteger)) orig)(self, _cmd, index);
  [self didChange: NSKeyValueChangeRemoval valuesAtIndexes: indexes forKey: key];
}
static void
portableRemoveAtIndexes(id self, SEL _cmd, NSIndexSet *indexes)
{
  NSString	*key;
  IMP		orig;

  _NSKVOPortableLookup(self, _cmd, &key, &orig);
  [self willChange: NSKeyValueChangeRemoval valuesAtIndexes: indexes forKey: key];
  ((void (*)(id, SEL, NSIndexSet *)) orig)(self, _cmd, indexes);
  [self didChange: NSKeyValueChangeRemoval valuesAtIndexes: indexes forKey: key];
}
static void
portableReplaceObjectAtIndex(id self, SEL _cmd, NSUInteger index, id object)
{
  NSString	*key;
  IMP		orig;
  NSIndexSet	*indexes = [NSIndexSet indexSetWithIndex: index];

  _NSKVOPortableLookup(self, _cmd, &key, &orig);
  [self willChange: NSKeyValueChangeReplacement valuesAtIndexes: indexes forKey: key];
  ((void (*)(id, SEL, NSUInteger, id)) orig)(self, _cmd, index, object);
  [self didChange: NSKeyValueChangeReplacement valuesAtIndexes: indexes forKey: key];
}
static void
portableReplaceAtIndexes(id self, SEL _cmd, NSIndexSet *indexes, id objects)
{
  NSString	*key;
  IMP		orig;

  _NSKVOPortableLookup(self, _cmd, &key, &orig);
  [self willChange: NSKeyValueChangeReplacement valuesAtIndexes: indexes forKey: key];
  ((void (*)(id, SEL, NSIndexSet *, id)) orig)(self, _cmd, indexes, objects);
  [self didChange: NSKeyValueChangeReplacement valuesAtIndexes: indexes forKey: key];
}

/* Unordered (set to-many) mutation notifiers. */
#define GENERATE_PORTABLE_SETDISPATCH(funcName, Kind)                          \
  static void funcName(id self, SEL _cmd, NSSet *set)                          \
  {                                                                            \
    NSString *key;                                                             \
    IMP       orig;                                                            \
    _NSKVOPortableLookup(self, _cmd, &key, &orig);                             \
    [self willChangeValueForKey: key withSetMutation: Kind usingObjects: set]; \
    ((void (*)(id, SEL, NSSet *)) orig)(self, _cmd, set);                      \
    [self didChangeValueForKey: key withSetMutation: Kind usingObjects: set];  \
  }
#define GENERATE_PORTABLE_SETDISPATCH_INDIVIDUAL(funcName, Kind)               \
  static void funcName(id self, SEL _cmd, id obj)                              \
  {                                                                            \
    NSSet    *set = [NSSet setWithObject: obj];                                \
    NSString *key;                                                             \
    IMP       orig;                                                            \
    _NSKVOPortableLookup(self, _cmd, &key, &orig);                             \
    [self willChangeValueForKey: key withSetMutation: Kind usingObjects: set]; \
    ((void (*)(id, SEL, id)) orig)(self, _cmd, obj);                           \
    [self didChangeValueForKey: key withSetMutation: Kind usingObjects: set];  \
  }
GENERATE_PORTABLE_SETDISPATCH_INDIVIDUAL(portableUnionIndividual,
  NSKeyValueUnionSetMutation);
GENERATE_PORTABLE_SETDISPATCH_INDIVIDUAL(portableMinusIndividual,
  NSKeyValueMinusSetMutation);
GENERATE_PORTABLE_SETDISPATCH(portableUnionSet, NSKeyValueUnionSetMutation);
GENERATE_PORTABLE_SETDISPATCH(portableMinusSet, NSKeyValueMinusSetMutation);
GENERATE_PORTABLE_SETDISPATCH(portableIntersectSet,
  NSKeyValueIntersectSetMutation);

/* Dictionary (arbitrary-key) mutation notifiers.  Unlike the setters above,
 * the key is the runtime argument rather than one derived from the selector,
 * so the cached key from the lookup is unused. */
static void
portableSetObjectForKey(id self, SEL _cmd, id object, NSString *key)
{
  NSString	*unused;
  IMP		orig;

  _NSKVOPortableLookup(self, _cmd, &unused, &orig);
  [self willChangeValueForKey: key];
  ((void (*)(id, SEL, id, NSString *)) orig)(self, _cmd, object, key);
  [self didChangeValueForKey: key];
}
static void
portableRemoveObjectForKey(id self, SEL _cmd, NSString *key)
{
  NSString	*unused;
  IMP		orig;

  _NSKVOPortableLookup(self, _cmd, &unused, &orig);
  [self willChangeValueForKey: key];
  ((void (*)(id, SEL, NSString *)) orig)(self, _cmd, key);
  [self didChangeValueForKey: key];
}

static SEL
formatSelector(NSString *format, ...)
{
  NSString	*s;
  SEL		sel;
  va_list	ap;

  va_start(ap, format);
  s = [[NSString alloc] initWithFormat: format arguments: ap];
  sel = NSSelectorFromString([s autorelease]);
  va_end(ap);
  return sel;
}

/* Override sel on the notifying subclass with notifyImp (once per selector),
 * caching the original implementation and the KVC key for the setter body. */
static void
_NSKVOInstallOverride(id object, _NSKVOSwizzledClass *info, SEL sel,
  NSString *key, IMP notifyImp)
{
  Method	m;

  if ((SEL) 0 == sel || ![object respondsToSelector: sel])
    {
      return;
    }
  GS_MUTEX_LOCK(kvoSwizzleLock);
  {
    if (NSMapGet(info->impForSelector, sel_getName(sel)) == NULL)
      {
	m = class_getInstanceMethod(_NSKVOPublicClass(object), sel);
	if (NULL == m)
	  {
	    GS_MUTEX_UNLOCK(kvoSwizzleLock);
	    return;
	  }
	NSMapInsert(info->keyForSelector, sel_getName(sel), key);
	NSMapInsert(info->impForSelector, sel_getName(sel),
	  (void *) method_getImplementation(m));
	class_addMethod(info->subclass, sel, notifyImp,
	  method_getTypeEncoding(m));
      }
  }
  GS_MUTEX_UNLOCK(kvoSwizzleLock);
}

/* invariant: rawKey has already been capitalized */
static inline void
_NSKVOEnsureSimpleKeyWillNotify(id object, _NSKVOSwizzledClass *info,
  NSString *key, const char *rawKey)
{
  SEL			sel = KVCSetterForPropertyName(object, rawKey);
  Method		originalMethod;
  const char		*types;
  const char		*valueType;
  NSMethodSignature	*sig;
  IMP			newImpl = NULL;

  if ((SEL) 0 == sel)
    {
      return;
    }
  originalMethod = class_getInstanceMethod(_NSKVOPublicClass(object), sel);
  types = method_getTypeEncoding(originalMethod);
  if (!types)
    {
      return;
    }
  sig = [NSMethodSignature signatureWithObjCTypes: types];
  valueType = [sig getArgumentTypeAtIndex: 2];

  switch (valueType[0])
    {
      OBJC_APPLY_ALL_TYPE_ENCODINGS(KVO_SET_IMPL_CASE);
      case '{':
      case '[':
	{
	  size_t valueSize = objc_sizeof_type(valueType);

	  if (valueSize > 6 * sizeof(uintptr_t))
	    {
	      [NSException raise: NSInvalidArgumentException
			  format: @"Class %s key %@ has a value size of %u bytes"
		@", and cannot currently be KVO compliant.",
		class_getName(_NSKVOPublicClass(object)), key,
		(unsigned int) valueSize];
	    }
	  newImpl = (IMP) (&portableVariadicSetImpl);
	  break;
	}
      default:
	[NSException raise: NSInvalidArgumentException
		    format: @"Class %s is not KVO compliant for key %@.",
	  class_getName(_NSKVOPublicClass(object)), key];
	return;
    }
  _NSKVOInstallOverride(object, info, sel, key, newImpl);
}

/* invariant: rawKey has already been capitalized */
static inline void
_NSKVOEnsureOrderedCollectionWillNotify(id object, _NSKVOSwizzledClass *info,
  NSString *key, const char *rawKey)
{
  SEL insertOne = formatSelector(@"insertObject:in%sAtIndex:", rawKey);
  SEL insertMany = formatSelector(@"insert%s:atIndexes:", rawKey);

  if ([object respondsToSelector: insertOne]
    || [object respondsToSelector: insertMany])
    {
      _NSKVOInstallOverride(object, info, insertOne, key,
	(IMP) portableInsertObjectAtIndex);
      _NSKVOInstallOverride(object, info, insertMany, key,
	(IMP) portableInsertAtIndexes);
      _NSKVOInstallOverride(object, info,
	formatSelector(@"removeObjectFrom%sAtIndex:", rawKey), key,
	(IMP) portableRemoveObjectAtIndex);
      _NSKVOInstallOverride(object, info,
	formatSelector(@"remove%sAtIndexes:", rawKey), key,
	(IMP) portableRemoveAtIndexes);
      _NSKVOInstallOverride(object, info,
	formatSelector(@"replaceObjectIn%sAtIndex:withObject:", rawKey), key,
	(IMP) portableReplaceObjectAtIndex);
      _NSKVOInstallOverride(object, info,
	formatSelector(@"replace%sAtIndexes:with%s:", rawKey, rawKey), key,
	(IMP) portableReplaceAtIndexes);
    }
}

/* invariant: rawKey has already been capitalized */
static inline void
_NSKVOEnsureUnorderedCollectionWillNotify(id object, _NSKVOSwizzledClass *info,
  NSString *key, const char *rawKey)
{
  SEL addOne = formatSelector(@"add%sObject:", rawKey);
  SEL addMany = formatSelector(@"add%s:", rawKey);
  SEL removeOne = formatSelector(@"remove%sObject:", rawKey);
  SEL removeMany = formatSelector(@"remove%s:", rawKey);

  if (([object respondsToSelector: addOne]
    || [object respondsToSelector: addMany])
    && ([object respondsToSelector: removeOne]
      || [object respondsToSelector: removeMany]))
    {
      _NSKVOInstallOverride(object, info, addOne, key,
	(IMP) portableUnionIndividual);
      _NSKVOInstallOverride(object, info, addMany, key,
	(IMP) portableUnionSet);
      _NSKVOInstallOverride(object, info, removeOne, key,
	(IMP) portableMinusIndividual);
      _NSKVOInstallOverride(object, info, removeMany, key,
	(IMP) portableMinusSet);
      _NSKVOInstallOverride(object, info,
	formatSelector(@"intersect%s:", rawKey), key,
	(IMP) portableIntersectSet);
    }
}

/* Make the object notify for arbitrary-key mutations, as NSMutableDictionary
 * does, by overriding setObject:forKey: and removeObjectForKey: when present. */
static inline void
_NSKVOEnsureObjectIsKVOAware(id object, _NSKVOSwizzledClass *info)
{
  _NSKVOInstallOverride(object, info, @selector(setObject:forKey:),
    @"", (IMP) portableSetObjectForKey);
  _NSKVOInstallOverride(object, info, @selector(removeObjectForKey:),
    @"", (IMP) portableRemoveObjectForKey);
}

/* NSKVOEnsureKeyWillNotify is the main entrypoint into the swizzling code. */
void
_NSKVOEnsureKeyWillNotify(id object, NSString *key)
{
  char			*rawKey;
  Class			cls;
  Class			underlyingCls;
  _NSKVOSwizzledClass	*info;

  cls = [object class];
  underlyingCls = [object _underlyingClass];
  /* If cls differs from underlyingCls, object is actually a proxy. */
  if (cls != underlyingCls)
    {
      object = [object valueForKey: @"self"];
    }

  if (![underlyingCls automaticallyNotifiesObserversForKey: key])
    {
      return;
    }

  rawKey = mutableBufferFromString(key);
  rawKey[0] = toupper(rawKey[0]);

  GS_MUTEX_LOCK(kvoSwizzleLock);
  {
    info = _NSKVOInfoForClass(_NSKVOPublicClass(object));
    _NSKVOEnsureSimpleKeyWillNotify(object, info, key, rawKey);
    _NSKVOEnsureOrderedCollectionWillNotify(object, info, key, rawKey);
    _NSKVOEnsureUnorderedCollectionWillNotify(object, info, key, rawKey);
    _NSKVOEnsureObjectIsKVOAware(object, info);
    if (object_getClass(object) != info->subclass)
      {
	object_setClass(object, info->subclass);
      }
  }
  GS_MUTEX_UNLOCK(kvoSwizzleLock);

  free(rawKey);
}

#endif
