
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = NSZombie processgroup testcat testecho

NSZombie_OBJC_FILES = NSZombie.m
NSZombie_NEEDS_GUI = NO

processgroup_OBJC_FILES = processgroup.m
processgroup_NEEDS_GUI = NO

testcat_OBJC_FILES = testcat.m
testcat_NEEDS_GUI = NO

testecho_OBJC_FILES = testecho.m
testecho_NEEDS_GUI = NO

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

