
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = NSZombie processgroup testcat testecho testsleep testpwd teststdio testenvvar testsimple

NEEDS_GUI = NO

NSZombie_OBJC_FILES = NSZombie.m

processgroup_OBJC_FILES = processgroup.m

testcat_C_FILES = testcat.c

testecho_OBJC_FILES = testecho.m

testsleep_OBJC_FILES = testsleep.m

testpwd_OBJC_FILES = testpwd.m

teststdio_OBJC_FILES = teststdio.m

testenvvar_OBJC_FILES = testenvvar.m

testsimple_OBJC_FILES = testsimple.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

